services:

  # works but doesn't display the setup-config.php page nicely.
  phphttp:
    container_name: phphttp
    build:
      context: .
      dockerfile: ../LocalServer/templates/FrankenPHP/Dockerfile
    expose:
      - "80"
      - "443"
    volumes:
      - ./www:/app/public
      - caddy_data:/data
      - caddy_config:/config
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`wordpress.cy`)
      - traefik.http.routers.wordpress.entrypoints=websecure
      - traefik.http.services.wordpress.loadbalancer.server.port=80
      - traefik.http.routers.wordpress.tls=true
    environment:
      - "SERVER_NAME=:80"
  
  # Not working, see comment.
  # phphttps: 
  #   container_name: phphttps
  #   tty: true
  #   build:
  #     context: .
  #     dockerfile: ../LocalServer/templates/FrankenPHP/Dockerfile
  #   expose:
  #     - "80"
  #     - "443"
  #   volumes:
  #     - ./www:/app/public
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.phphttps.rule=Host(`phphttps.cy`)
  #     - traefik.http.routers.phphttps.entrypoints=websecure
  #     - traefik.http.services.phphttps.loadbalancer.server.port=443
  #     - traefik.http.services.phphttps.loadbalancer.scheme=https # This makes the container fail..
  #     - traefik.http.routers.phphttps.tls=true

  # db:
  #   image: mariadb:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

volumes:
  caddy_data:
  caddy_config:
  db_data:


networks:
  default:
    name: syma
    external: true
