services:
  dashboard:
    image: "nginx:latest"
    container_name: "dashboard"
    volumes:
      - "./www:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.cy`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      # - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.tls=true"
    restart: always

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--configFile=/etc/traefik/config.yml"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik:/etc/traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.cy`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.middlewares.api-cors.headers.accessControlAllowOriginList=*"
      - "traefik.http.routers.traefik.middlewares=api-cors"
    restart: always

  dns:
    container_name: dns
    image: cytopia/bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - "53"
    environment:
      - DNS_A=*.cy=127.0.0.1
      - DNS_FORWARDER=1.1.1.1
      - DOCKER_LOGS=0
      - DEBUG_ENTRYPOINT=2
      - ALLOW_RECURSION=any
    restart: always
    volumes:
      - "./config/cy.conf:/etc/bind/cy.conf"
      - "./config/db.cy:/etc/bind/db.cy"

  # whoami:
  #   image: "traefik/whoami"
  #   container_name: "simple-service"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.cy`)"
  #     - "traefik.http.routers.whoami.entrypoints=websecure"
  #     - "traefik.http.routers.whoami.tls=true"
  #   restart: always

  # phptest:
  #   image: dunglas/frankenphp
  #   container_name: "phptest"
  #   volumes:
  #     - ./www:/app/public
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   tty: true
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.phptest.rule=Host(`test.cy`)"
  #     - "traefik.http.routers.phptest.entrypoints=websecure"
  #     - "traefik.http.routers.phptest.tls=true"
  #     - "traefik.http.services.phptest.loadbalancer.server.port=80"
  #   environment:
  #     - "SERVER_NAME=:80"
  #   restart: always
  
  stats:
    image: prom/prometheus:latest
    container_name: "stats"
    expose:
      - 9090
    ports:
      - 9090:9090
    volumes:
        - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stats.rule=Host(`stats.cy`)"
      - "traefik.http.routers.stats.entrypoints=websecure"
      - "traefik.http.services.stats.loadbalancer.server.port=9090"
      - "traefik.http.routers.stats.tls=true"
    restart: always
    
  mail:
    container_name: mail
    image: marlonb/mailcrab:latest
    expose:
      - 1080
      - 1025
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail.cy`)"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.services.mail.loadbalancer.server.port=1080"
      - "traefik.http.routers.mail.tls=true"
    restart: always

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    name: syma
    external: true



# networks:
#   syma:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: "172.90.1.0/24"