# Logging
log:
  level: DEBUG

# API
api:
  dashboard: true
  insecure: true
  debug: true

# Providers
providers:
  file:
    directory: /etc/traefik
    watch: true
  docker:
    watch: true
    exposedByDefault: false

# Entrypoints
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  metrics:
    address: ":8082"

# Metrics?
metrics:
  prometheus:
    entryPoint: metrics