services:
  scrappy:
    image: badouralix/python-scrapy
    container_name: "crawler-scrapy"
    restart: always

  php-fpm:
    build:
      context: .
      dockerfile: ../LocalServer/templates/WordPress/Dockerfile-root
    container_name: "crawler-wp"
    restart: always
    volumes:
      - "./www:/var/www/html"
      - "../LocalServer/templates/WordPress/php/custom.ini:/usr/local/etc/php/conf.d/z-custom.ini"
      - "/var/run/docker.sock:/var/run/docker.sock"

  nginx:
    image: nginx:latest
    container_name: "crawler-nginx"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crawler.rule=Host(`crawler.cy`)"
      - "traefik.http.routers.crawler.entrypoints=websecure"
      - "traefik.http.routers.crawler.tls=true"
    volumes:
      - "../LocalServer/templates/WordPress/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./www:/var/www/html"
    links:
      - php-fpm

  db:
    image: mariadb:latest
    container_name: "crawler-db"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:

networks:
  default:
    name: syma
    external: true
